# Generated by Django 2.2 on 2020-04-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
