# Generated by Django 2.2 on 2020-05-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='matricula',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='proprietario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
