# Generated by Django 2.2.10 on 2020-06-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200529_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_type', models.PositiveSmallIntegerField(choices=[(1, 'setor A Funcionarios'), (2, 'setor B Geral'), (3, 'setor C Geral'), (4, 'setor D Geral')])),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
            ],
        ),
    ]
